file = open("bucket list.txt", "w")
file.write("1. Fly a plane\n")
file.write("2. See a dolphin\n")
file.write("3. Create my own website for my resturant\n")
file.write('4. Skydive\n')
file.close()
print("Bucket  list saved to bucket list.txt")

file = open("bucket list.txt", "r")
content = file.read()
print("\n==== Bucket List ====")
print(content)
file.close()

file = open("bucket list.txt", "r")
lines = file.readlines()
print(f"You have {len(lines)} items in your bucket list.")
file.close()

file = open("bucket list.txt", "a")
file.write("4. Snowboard in the Alps\n")
file.write("5. Visit Japan\n")
file.close()
print("\n2 more items have been added to your bucket list.")

file = open("bucket list.txt", "r")
print("\n==== Updated Bucket list ====")
print(file.read())
file.close()